language: node_js
node_js:
  - "0.10"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y python-software-properties curl build-essential git fontconfig"
  - "curl -o ffmpeg.tar.xz http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz"
  - "sudo tar -vxJf ffmpeg.tar.xz -C /usr/bin"

install:
  - npm install
  - npm install -g bower
  - bower install
before_script:
  - "gulp build -o"
